### ISSUE TITLE
Current role do not allow pi-hole upgrade

### ISSUE THREAD

**Issue by chubchubsancho** [chubchubsancho/ansible-pi-hole#10]
Based on current installation task, we are unable to perform `pi-hole` upgrade.

currently we check if `pi-hiole` is already installed through this task
```yaml
- name: "check if pi-hole is already installed"
  ansible.builtin.stat:
    path: "/opt/pihole"
  register: pihole_installed
  tags:
    - pihole
    - installation
    - check
 ```
and next tasks are only run if `pihole_installed.stat.isdir is undefined`
